import { COMMON_ERROR_STATUS_MAP } from "@orpc/openapi";

export const errorStatusMap = {
  ...COMMON_ERROR_STATUS_MAP,
  INVALID_REPOSITORY: 400,
  REPOSITORY_NOT_FOUND: 404,
  GITHUB_UNAVAILABLE: 502,
  REPOSITORY_SAVE_FAILED: 502,
  REVIEW_QUEUE_UNAVAILABLE: 502,
  REVIEW_CREATE_FAILED: 502,
  REVIEW_NOT_FOUND: 404,
  REVIEW_STATE_CONFLICT: 409,
};
