name: CI

on: [push]

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm and node
        uses: pnpm/setup@v2.1.0
        with:
          working-directory: apps/web
          version: 12.4.1
          runtime: node@24
          cache: true
          require-lockfile: true

      - run: pnpm format:check
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build
